spring:
  application:
    name: student-db

  datasource:
    url: jdbc:mysql://localhost:3306/ #db Name
    username: #userId
    password: #password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
